version: '3.0'

services:
  budgety_nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - budgety_redis
    restart: always
  postgres:
    image: postgres
    ports:
      - "5480:5432"
    env_file:
      - .postgres
    volumes:
      - budgety_nestjs_local_db:/var/lib/postgresql/data
      - budgety_nestjs_local_backups:/backups
    restart: always
  budgety_redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  
volumes:
  budgety_nestjs_local_db: 
    driver: local
    
  budgety_nestjs_local_backups: 
    driver: local
  
    