name: Budgety Dev Server

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 18.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set-matrix
        run: |
          echo $DEV_SECRET
        env:
          DEV_SECRET: ${{secrets.DEV_SECRET}}

      - name: get matrix
        run: echo ${{ steps.set-matrix.outputs.matrix }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
