name: Budgety Production Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: |
          flyctl deploy --remote-only --build-arg VAULT_TOKEN=${{secrets.VAULT_TOKEN}}
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
