name: Budgety Production Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only --build-arg APP_ENV=${{secrets.APP_ENV}}
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
